title: Personal Deadlines
description: Personal tracker for conferences, projects, and milestones.
author: DuanYuFi

domain: "duanyufi.github.io"
baseurl: "/deadlines"

twitter_username: hiddenmarkov
github_username: DuanYuFi
github_repo: deadlines
ga_id: UA-104921371-1

markdown: kramdown

